<var><Id,a><,><Id,b><,><Id,c><,><Id,d><,><Id,s><:><integer><;>
<begin>
<Id,a><:=><num,3><;>
<Id,b><:=><num,23><;>
<Id,c><:=><num,12.52><;>
<Id,d><:=><num,255><;>
<Id,s><:=><Id,a><+><Id,b><+><Id,c><+><Id,d><;>
<writeln><(><Id,s><)><;>
<end>
